"""
This module imports the wrs_main_node module as wrs.
"""

import wrs_main_node as wrs

position_list = [
          "position_1",
          "position_2",
          "position_3",
          "position_4",
          "position_5",
          "position_6",
          "position_7",
          "position_8",
          "position_9",
          "position_10",
          "position_11",
          "position_12",
          "position_13",
          "position_14",
          "position_15",
          "position_16",
          "position_17",
          "position_18",
          "position_19",
          "position_20",
          "position_21",
          "position_22",
          "position_23",
          "position_24",
          "position_25",
          "position_26",
          "position_27",
          "position_28",
          "position_29",
          "position_30",
          "position_31",
          "position_32",
          "position_33",
          "position_34",
          "position_35",
          "position_36",
          "position_37",
          "position_38",
          "position_39",
          "position_40",
          "position_41",
          "position_42",
          "position_43",
          "position_44",
          "position_45",
          "position_46",
          "position_47",
          "position_48",
          "position_49",
          "position_50",
          "position_51",
          "position_52",
          "position_53",
          "position_54",
          "position_55",
          "position_56",
          "position_57",
          "position_58",
          "position_59",
          "position_60",
          "position_61",
          "position_62",
          "position_63",
          "position_64",
          "position_65",
          "position_66",
          "position_67",
          "position_68",
          "position_69",
          "position_70",
          "position_71",
          "position_72",
          "position_73",
          "position_74",
          "position_75",
          "position_76",
          "position_77",
          "position_78"
      ]
def positionChecker():
    rospy.loginfo("####  Task Checker ####")
    for plc in position_list:
        self.put_in_place(plc, "put_in_bin")
